name: lab3

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: brbr
        run: sudo apt-get -y update && \ 
           sudo export DEBIAN_FRONTEND=noninteractive && \
           sudo export TZ=Europe/Moscow && \
           sudo apt-get -y install gcc g++ make cmake && \
           sudo g++ --version && \
           sudo ./gomake && \
           sudo chmod +x test/make-result* && \
           sudo chmod +x test/test && \
           sudo chmod +x test/stress && \
           sudo test/test && \
           sudo test/stress